# Generated by Django 2.0.2 on 2018-06-16 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='UserAccount',
        ),
        migrations.AddField(
            model_name='message',
            name='UserThatPosted',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.UserSettings'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messagelike',
            name='UserWhoLiked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserSettings'),
        ),
    ]
